FROM golang:latest as go_builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -a -o main .

FROM alpine:latest
COPY --from=go_builder /app/main .
EXPOSE 8080

CMD [ "./main" ]
