// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: model/proto_model/node.proto

package proto_model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_AVAILABLE   Status = 1
	Status_STATUS_UNAVAILABLE Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_AVAILABLE",
		2: "STATUS_UNAVAILABLE",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_AVAILABLE":   1,
		"STATUS_UNAVAILABLE": 2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_model_proto_model_node_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_model_proto_model_node_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_model_proto_model_node_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_model_proto_model_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_model_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_model_proto_model_node_proto_rawDescGZIP(), []int{0}
}

type CreateNodeRequirements struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           int64                  `protobuf:"varint,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        int64                  `protobuf:"varint,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Storage       int64                  `protobuf:"varint,3,opt,name=storage,proto3" json:"storage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNodeRequirements) Reset() {
	*x = CreateNodeRequirements{}
	mi := &file_model_proto_model_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNodeRequirements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNodeRequirements) ProtoMessage() {}

func (x *CreateNodeRequirements) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_model_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNodeRequirements.ProtoReflect.Descriptor instead.
func (*CreateNodeRequirements) Descriptor() ([]byte, []int) {
	return file_model_proto_model_node_proto_rawDescGZIP(), []int{1}
}

func (x *CreateNodeRequirements) GetCpu() int64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *CreateNodeRequirements) GetMemory() int64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *CreateNodeRequirements) GetStorage() int64 {
	if x != nil {
		return x.Storage
	}
	return 0
}

// create master
type CreateMasterRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Token         string                  `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Requirements  *CreateNodeRequirements `protobuf:"bytes,2,opt,name=requirements,proto3" json:"requirements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMasterRequest) Reset() {
	*x = CreateMasterRequest{}
	mi := &file_model_proto_model_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMasterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMasterRequest) ProtoMessage() {}

func (x *CreateMasterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_model_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMasterRequest.ProtoReflect.Descriptor instead.
func (*CreateMasterRequest) Descriptor() ([]byte, []int) {
	return file_model_proto_model_node_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMasterRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreateMasterRequest) GetRequirements() *CreateNodeRequirements {
	if x != nil {
		return x.Requirements
	}
	return nil
}

type CreateMasterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpAddress     string                 `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMasterResponse) Reset() {
	*x = CreateMasterResponse{}
	mi := &file_model_proto_model_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMasterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMasterResponse) ProtoMessage() {}

func (x *CreateMasterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_model_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMasterResponse.ProtoReflect.Descriptor instead.
func (*CreateMasterResponse) Descriptor() ([]byte, []int) {
	return file_model_proto_model_node_proto_rawDescGZIP(), []int{3}
}

func (x *CreateMasterResponse) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

// create worker
type CreateWorkerRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Token         string                  `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	IpAddress     string                  `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Requirements  *CreateNodeRequirements `protobuf:"bytes,3,opt,name=requirements,proto3" json:"requirements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkerRequest) Reset() {
	*x = CreateWorkerRequest{}
	mi := &file_model_proto_model_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkerRequest) ProtoMessage() {}

func (x *CreateWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_model_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkerRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkerRequest) Descriptor() ([]byte, []int) {
	return file_model_proto_model_node_proto_rawDescGZIP(), []int{4}
}

func (x *CreateWorkerRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreateWorkerRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *CreateWorkerRequest) GetRequirements() *CreateNodeRequirements {
	if x != nil {
		return x.Requirements
	}
	return nil
}

type CreateWorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkerResponse) Reset() {
	*x = CreateWorkerResponse{}
	mi := &file_model_proto_model_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkerResponse) ProtoMessage() {}

func (x *CreateWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_model_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkerResponse.ProtoReflect.Descriptor instead.
func (*CreateWorkerResponse) Descriptor() ([]byte, []int) {
	return file_model_proto_model_node_proto_rawDescGZIP(), []int{5}
}

// create instance
type CreateInstanceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// top-level name of the cluster
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// true if spawning master instance
	// false otherwise
	IsMaster bool `protobuf:"varint,2,opt,name=is_master,json=isMaster,proto3" json:"is_master,omitempty"`
	// token for creating k3s cluster
	// only needed when spawning worker
	// token will created when spawning master
	Token string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	// ip address of the master instance
	// only needed when spawning worker
	IpAddress string `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	// instance hardware requirements
	Cpu           int64 `protobuf:"varint,5,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        int64 `protobuf:"varint,6,opt,name=memory,proto3" json:"memory,omitempty"`
	Storage       int64 `protobuf:"varint,7,opt,name=storage,proto3" json:"storage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInstanceRequest) Reset() {
	*x = CreateInstanceRequest{}
	mi := &file_model_proto_model_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInstanceRequest) ProtoMessage() {}

func (x *CreateInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_model_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInstanceRequest.ProtoReflect.Descriptor instead.
func (*CreateInstanceRequest) Descriptor() ([]byte, []int) {
	return file_model_proto_model_node_proto_rawDescGZIP(), []int{6}
}

func (x *CreateInstanceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateInstanceRequest) GetIsMaster() bool {
	if x != nil {
		return x.IsMaster
	}
	return false
}

func (x *CreateInstanceRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreateInstanceRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *CreateInstanceRequest) GetCpu() int64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *CreateInstanceRequest) GetMemory() int64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *CreateInstanceRequest) GetStorage() int64 {
	if x != nil {
		return x.Storage
	}
	return 0
}

type CreateInstanceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// returns ip address of master instance
	IpAddress     string `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInstanceResponse) Reset() {
	*x = CreateInstanceResponse{}
	mi := &file_model_proto_model_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInstanceResponse) ProtoMessage() {}

func (x *CreateInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_model_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInstanceResponse.ProtoReflect.Descriptor instead.
func (*CreateInstanceResponse) Descriptor() ([]byte, []int) {
	return file_model_proto_model_node_proto_rawDescGZIP(), []int{7}
}

func (x *CreateInstanceResponse) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

var File_model_proto_model_node_proto protoreflect.FileDescriptor

const file_model_proto_model_node_proto_rawDesc = "" +
	"\n" +
	"\x1cmodel/proto_model/node.proto\"\a\n" +
	"\x05Empty\"\\\n" +
	"\x16CreateNodeRequirements\x12\x10\n" +
	"\x03cpu\x18\x01 \x01(\x03R\x03cpu\x12\x16\n" +
	"\x06memory\x18\x02 \x01(\x03R\x06memory\x12\x18\n" +
	"\astorage\x18\x03 \x01(\x03R\astorage\"h\n" +
	"\x13CreateMasterRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12;\n" +
	"\frequirements\x18\x02 \x01(\v2\x17.CreateNodeRequirementsR\frequirements\"5\n" +
	"\x14CreateMasterResponse\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x01 \x01(\tR\tipAddress\"\x87\x01\n" +
	"\x13CreateWorkerRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12;\n" +
	"\frequirements\x18\x03 \x01(\v2\x17.CreateNodeRequirementsR\frequirements\"\x16\n" +
	"\x14CreateWorkerResponse\"\xc1\x01\n" +
	"\x15CreateInstanceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tis_master\x18\x02 \x01(\bR\bisMaster\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\x12\x10\n" +
	"\x03cpu\x18\x05 \x01(\x03R\x03cpu\x12\x16\n" +
	"\x06memory\x18\x06 \x01(\x03R\x06memory\x12\x18\n" +
	"\astorage\x18\a \x01(\x03R\astorage\"7\n" +
	"\x16CreateInstanceResponse\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x01 \x01(\tR\tipAddress*N\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10STATUS_AVAILABLE\x10\x01\x12\x16\n" +
	"\x12STATUS_UNAVAILABLE\x10\x022\xd0\x01\n" +
	"\vNodeService\x12=\n" +
	"\fCreateMaster\x12\x14.CreateMasterRequest\x1a\x15.CreateMasterResponse\"\x00\x12=\n" +
	"\fCreateWorker\x12\x14.CreateWorkerRequest\x1a\x15.CreateWorkerResponse\"\x00\x12C\n" +
	"\x0eCreateInstance\x12\x16.CreateInstanceRequest\x1a\x17.CreateInstanceResponse\"\x00B\x15Z\x13./model/proto_modelb\x06proto3"

var (
	file_model_proto_model_node_proto_rawDescOnce sync.Once
	file_model_proto_model_node_proto_rawDescData []byte
)

func file_model_proto_model_node_proto_rawDescGZIP() []byte {
	file_model_proto_model_node_proto_rawDescOnce.Do(func() {
		file_model_proto_model_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_proto_model_node_proto_rawDesc), len(file_model_proto_model_node_proto_rawDesc)))
	})
	return file_model_proto_model_node_proto_rawDescData
}

var file_model_proto_model_node_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_model_proto_model_node_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_model_proto_model_node_proto_goTypes = []any{
	(Status)(0),                    // 0: Status
	(*Empty)(nil),                  // 1: Empty
	(*CreateNodeRequirements)(nil), // 2: CreateNodeRequirements
	(*CreateMasterRequest)(nil),    // 3: CreateMasterRequest
	(*CreateMasterResponse)(nil),   // 4: CreateMasterResponse
	(*CreateWorkerRequest)(nil),    // 5: CreateWorkerRequest
	(*CreateWorkerResponse)(nil),   // 6: CreateWorkerResponse
	(*CreateInstanceRequest)(nil),  // 7: CreateInstanceRequest
	(*CreateInstanceResponse)(nil), // 8: CreateInstanceResponse
}
var file_model_proto_model_node_proto_depIdxs = []int32{
	2, // 0: CreateMasterRequest.requirements:type_name -> CreateNodeRequirements
	2, // 1: CreateWorkerRequest.requirements:type_name -> CreateNodeRequirements
	3, // 2: NodeService.CreateMaster:input_type -> CreateMasterRequest
	5, // 3: NodeService.CreateWorker:input_type -> CreateWorkerRequest
	7, // 4: NodeService.CreateInstance:input_type -> CreateInstanceRequest
	4, // 5: NodeService.CreateMaster:output_type -> CreateMasterResponse
	6, // 6: NodeService.CreateWorker:output_type -> CreateWorkerResponse
	8, // 7: NodeService.CreateInstance:output_type -> CreateInstanceResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_model_proto_model_node_proto_init() }
func file_model_proto_model_node_proto_init() {
	if File_model_proto_model_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_proto_model_node_proto_rawDesc), len(file_model_proto_model_node_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_model_proto_model_node_proto_goTypes,
		DependencyIndexes: file_model_proto_model_node_proto_depIdxs,
		EnumInfos:         file_model_proto_model_node_proto_enumTypes,
		MessageInfos:      file_model_proto_model_node_proto_msgTypes,
	}.Build()
	File_model_proto_model_node_proto = out.File
	file_model_proto_model_node_proto_goTypes = nil
	file_model_proto_model_node_proto_depIdxs = nil
}
