// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: services/model/proto-model/node.proto

package proto_model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_services_model_proto_model_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_services_model_proto_model_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_services_model_proto_model_node_proto_rawDescGZIP(), []int{0}
}

type CreationStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreationStatus) Reset() {
	*x = CreationStatus{}
	mi := &file_services_model_proto_model_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreationStatus) ProtoMessage() {}

func (x *CreationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_services_model_proto_model_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreationStatus.ProtoReflect.Descriptor instead.
func (*CreationStatus) Descriptor() ([]byte, []int) {
	return file_services_model_proto_model_node_proto_rawDescGZIP(), []int{1}
}

func (x *CreationStatus) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreationStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateNodeRequirements struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Vcpu          int32                  `protobuf:"varint,2,opt,name=vcpu,proto3" json:"vcpu,omitempty"`
	Memory        int32                  `protobuf:"varint,3,opt,name=memory,proto3" json:"memory,omitempty"`
	Storage       int32                  `protobuf:"varint,4,opt,name=storage,proto3" json:"storage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNodeRequirements) Reset() {
	*x = CreateNodeRequirements{}
	mi := &file_services_model_proto_model_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNodeRequirements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNodeRequirements) ProtoMessage() {}

func (x *CreateNodeRequirements) ProtoReflect() protoreflect.Message {
	mi := &file_services_model_proto_model_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNodeRequirements.ProtoReflect.Descriptor instead.
func (*CreateNodeRequirements) Descriptor() ([]byte, []int) {
	return file_services_model_proto_model_node_proto_rawDescGZIP(), []int{2}
}

func (x *CreateNodeRequirements) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *CreateNodeRequirements) GetVcpu() int32 {
	if x != nil {
		return x.Vcpu
	}
	return 0
}

func (x *CreateNodeRequirements) GetMemory() int32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *CreateNodeRequirements) GetStorage() int32 {
	if x != nil {
		return x.Storage
	}
	return 0
}

// create master
type CreateMasterRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	ClusterName   string                  `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	ClusterToken  string                  `protobuf:"bytes,2,opt,name=cluster_token,json=clusterToken,proto3" json:"cluster_token,omitempty"`
	ClusterId     string                  `protobuf:"bytes,3,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Requirements  *CreateNodeRequirements `protobuf:"bytes,4,opt,name=requirements,proto3" json:"requirements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMasterRequest) Reset() {
	*x = CreateMasterRequest{}
	mi := &file_services_model_proto_model_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMasterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMasterRequest) ProtoMessage() {}

func (x *CreateMasterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_model_proto_model_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMasterRequest.ProtoReflect.Descriptor instead.
func (*CreateMasterRequest) Descriptor() ([]byte, []int) {
	return file_services_model_proto_model_node_proto_rawDescGZIP(), []int{3}
}

func (x *CreateMasterRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *CreateMasterRequest) GetClusterToken() string {
	if x != nil {
		return x.ClusterToken
	}
	return ""
}

func (x *CreateMasterRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *CreateMasterRequest) GetRequirements() *CreateNodeRequirements {
	if x != nil {
		return x.Requirements
	}
	return nil
}

type CreateMasterResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CreationStatus     *CreationStatus        `protobuf:"bytes,1,opt,name=creation_status,json=creationStatus,proto3" json:"creation_status,omitempty"`
	MasterIpAddress    string                 `protobuf:"bytes,2,opt,name=master_ip_address,json=masterIpAddress,proto3" json:"master_ip_address,omitempty"`
	DashboardToken     string                 `protobuf:"bytes,3,opt,name=dashboard_token,json=dashboardToken,proto3" json:"dashboard_token,omitempty"`
	KubeconfigContents []byte                 `protobuf:"bytes,4,opt,name=kubeconfig_contents,json=kubeconfigContents,proto3" json:"kubeconfig_contents,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateMasterResponse) Reset() {
	*x = CreateMasterResponse{}
	mi := &file_services_model_proto_model_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMasterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMasterResponse) ProtoMessage() {}

func (x *CreateMasterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_model_proto_model_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMasterResponse.ProtoReflect.Descriptor instead.
func (*CreateMasterResponse) Descriptor() ([]byte, []int) {
	return file_services_model_proto_model_node_proto_rawDescGZIP(), []int{4}
}

func (x *CreateMasterResponse) GetCreationStatus() *CreationStatus {
	if x != nil {
		return x.CreationStatus
	}
	return nil
}

func (x *CreateMasterResponse) GetMasterIpAddress() string {
	if x != nil {
		return x.MasterIpAddress
	}
	return ""
}

func (x *CreateMasterResponse) GetDashboardToken() string {
	if x != nil {
		return x.DashboardToken
	}
	return ""
}

func (x *CreateMasterResponse) GetKubeconfigContents() []byte {
	if x != nil {
		return x.KubeconfigContents
	}
	return nil
}

// create worker
type CreateWorkerRequest struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	ClusterName     string                  `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	ClusterToken    string                  `protobuf:"bytes,2,opt,name=cluster_token,json=clusterToken,proto3" json:"cluster_token,omitempty"`
	MasterIpAddress string                  `protobuf:"bytes,3,opt,name=master_ip_address,json=masterIpAddress,proto3" json:"master_ip_address,omitempty"`
	Requirements    *CreateNodeRequirements `protobuf:"bytes,4,opt,name=requirements,proto3" json:"requirements,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateWorkerRequest) Reset() {
	*x = CreateWorkerRequest{}
	mi := &file_services_model_proto_model_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkerRequest) ProtoMessage() {}

func (x *CreateWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_model_proto_model_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkerRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkerRequest) Descriptor() ([]byte, []int) {
	return file_services_model_proto_model_node_proto_rawDescGZIP(), []int{5}
}

func (x *CreateWorkerRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *CreateWorkerRequest) GetClusterToken() string {
	if x != nil {
		return x.ClusterToken
	}
	return ""
}

func (x *CreateWorkerRequest) GetMasterIpAddress() string {
	if x != nil {
		return x.MasterIpAddress
	}
	return ""
}

func (x *CreateWorkerRequest) GetRequirements() *CreateNodeRequirements {
	if x != nil {
		return x.Requirements
	}
	return nil
}

type CreateWorkerResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CreationStatus *CreationStatus        `protobuf:"bytes,1,opt,name=creation_status,json=creationStatus,proto3" json:"creation_status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateWorkerResponse) Reset() {
	*x = CreateWorkerResponse{}
	mi := &file_services_model_proto_model_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkerResponse) ProtoMessage() {}

func (x *CreateWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_model_proto_model_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkerResponse.ProtoReflect.Descriptor instead.
func (*CreateWorkerResponse) Descriptor() ([]byte, []int) {
	return file_services_model_proto_model_node_proto_rawDescGZIP(), []int{6}
}

func (x *CreateWorkerResponse) GetCreationStatus() *CreationStatus {
	if x != nil {
		return x.CreationStatus
	}
	return nil
}

type NodeStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatusRequest) Reset() {
	*x = NodeStatusRequest{}
	mi := &file_services_model_proto_model_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatusRequest) ProtoMessage() {}

func (x *NodeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_model_proto_model_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatusRequest.ProtoReflect.Descriptor instead.
func (*NodeStatusRequest) Descriptor() ([]byte, []int) {
	return file_services_model_proto_model_node_proto_rawDescGZIP(), []int{7}
}

type NodeStatusResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FreeVcpu         uint32                 `protobuf:"varint,1,opt,name=free_vcpu,json=freeVcpu,proto3" json:"free_vcpu,omitempty"`
	StorageAvailable uint32                 `protobuf:"varint,2,opt,name=storage_available,json=storageAvailable,proto3" json:"storage_available,omitempty"`
	MemoryAvailable  uint32                 `protobuf:"varint,3,opt,name=memory_available,json=memoryAvailable,proto3" json:"memory_available,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NodeStatusResponse) Reset() {
	*x = NodeStatusResponse{}
	mi := &file_services_model_proto_model_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatusResponse) ProtoMessage() {}

func (x *NodeStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_model_proto_model_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatusResponse.ProtoReflect.Descriptor instead.
func (*NodeStatusResponse) Descriptor() ([]byte, []int) {
	return file_services_model_proto_model_node_proto_rawDescGZIP(), []int{8}
}

func (x *NodeStatusResponse) GetFreeVcpu() uint32 {
	if x != nil {
		return x.FreeVcpu
	}
	return 0
}

func (x *NodeStatusResponse) GetStorageAvailable() uint32 {
	if x != nil {
		return x.StorageAvailable
	}
	return 0
}

func (x *NodeStatusResponse) GetMemoryAvailable() uint32 {
	if x != nil {
		return x.MemoryAvailable
	}
	return 0
}

type DeleteInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceName  string                 `protobuf:"bytes,1,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInstanceRequest) Reset() {
	*x = DeleteInstanceRequest{}
	mi := &file_services_model_proto_model_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInstanceRequest) ProtoMessage() {}

func (x *DeleteInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_model_proto_model_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInstanceRequest.ProtoReflect.Descriptor instead.
func (*DeleteInstanceRequest) Descriptor() ([]byte, []int) {
	return file_services_model_proto_model_node_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteInstanceRequest) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

type DeleteInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInstanceResponse) Reset() {
	*x = DeleteInstanceResponse{}
	mi := &file_services_model_proto_model_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInstanceResponse) ProtoMessage() {}

func (x *DeleteInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_model_proto_model_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInstanceResponse.ProtoReflect.Descriptor instead.
func (*DeleteInstanceResponse) Descriptor() ([]byte, []int) {
	return file_services_model_proto_model_node_proto_rawDescGZIP(), []int{10}
}

var File_services_model_proto_model_node_proto protoreflect.FileDescriptor

const file_services_model_proto_model_node_proto_rawDesc = "" +
	"\n" +
	"%services/model/proto-model/node.proto\"\a\n" +
	"\x05Empty\"D\n" +
	"\x0eCreationStatus\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"{\n" +
	"\x16CreateNodeRequirements\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x12\n" +
	"\x04vcpu\x18\x02 \x01(\x05R\x04vcpu\x12\x16\n" +
	"\x06memory\x18\x03 \x01(\x05R\x06memory\x12\x18\n" +
	"\astorage\x18\x04 \x01(\x05R\astorage\"\xb9\x01\n" +
	"\x13CreateMasterRequest\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\x12#\n" +
	"\rcluster_token\x18\x02 \x01(\tR\fclusterToken\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x03 \x01(\tR\tclusterId\x12;\n" +
	"\frequirements\x18\x04 \x01(\v2\x17.CreateNodeRequirementsR\frequirements\"\xd6\x01\n" +
	"\x14CreateMasterResponse\x128\n" +
	"\x0fcreation_status\x18\x01 \x01(\v2\x0f.CreationStatusR\x0ecreationStatus\x12*\n" +
	"\x11master_ip_address\x18\x02 \x01(\tR\x0fmasterIpAddress\x12'\n" +
	"\x0fdashboard_token\x18\x03 \x01(\tR\x0edashboardToken\x12/\n" +
	"\x13kubeconfig_contents\x18\x04 \x01(\fR\x12kubeconfigContents\"\xc6\x01\n" +
	"\x13CreateWorkerRequest\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\x12#\n" +
	"\rcluster_token\x18\x02 \x01(\tR\fclusterToken\x12*\n" +
	"\x11master_ip_address\x18\x03 \x01(\tR\x0fmasterIpAddress\x12;\n" +
	"\frequirements\x18\x04 \x01(\v2\x17.CreateNodeRequirementsR\frequirements\"P\n" +
	"\x14CreateWorkerResponse\x128\n" +
	"\x0fcreation_status\x18\x01 \x01(\v2\x0f.CreationStatusR\x0ecreationStatus\"\x13\n" +
	"\x11NodeStatusRequest\"\x89\x01\n" +
	"\x12NodeStatusResponse\x12\x1b\n" +
	"\tfree_vcpu\x18\x01 \x01(\rR\bfreeVcpu\x12+\n" +
	"\x11storage_available\x18\x02 \x01(\rR\x10storageAvailable\x12)\n" +
	"\x10memory_available\x18\x03 \x01(\rR\x0fmemoryAvailable\"<\n" +
	"\x15DeleteInstanceRequest\x12#\n" +
	"\rinstance_name\x18\x01 \x01(\tR\finstanceName\"\x18\n" +
	"\x16DeleteInstanceResponse2\x89\x02\n" +
	"\vNodeService\x12=\n" +
	"\fCreateMaster\x12\x14.CreateMasterRequest\x1a\x15.CreateMasterResponse\"\x00\x12=\n" +
	"\fCreateWorker\x12\x14.CreateWorkerRequest\x1a\x15.CreateWorkerResponse\"\x00\x127\n" +
	"\n" +
	"NodeStatus\x12\x12.NodeStatusRequest\x1a\x13.NodeStatusResponse\"\x00\x12C\n" +
	"\x0eDeleteInstance\x12\x16.DeleteInstanceRequest\x1a\x17.DeleteInstanceResponse\"\x00B\x1eZ\x1c./services/model/proto-modelb\x06proto3"

var (
	file_services_model_proto_model_node_proto_rawDescOnce sync.Once
	file_services_model_proto_model_node_proto_rawDescData []byte
)

func file_services_model_proto_model_node_proto_rawDescGZIP() []byte {
	file_services_model_proto_model_node_proto_rawDescOnce.Do(func() {
		file_services_model_proto_model_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_model_proto_model_node_proto_rawDesc), len(file_services_model_proto_model_node_proto_rawDesc)))
	})
	return file_services_model_proto_model_node_proto_rawDescData
}

var file_services_model_proto_model_node_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_services_model_proto_model_node_proto_goTypes = []any{
	(*Empty)(nil),                  // 0: Empty
	(*CreationStatus)(nil),         // 1: CreationStatus
	(*CreateNodeRequirements)(nil), // 2: CreateNodeRequirements
	(*CreateMasterRequest)(nil),    // 3: CreateMasterRequest
	(*CreateMasterResponse)(nil),   // 4: CreateMasterResponse
	(*CreateWorkerRequest)(nil),    // 5: CreateWorkerRequest
	(*CreateWorkerResponse)(nil),   // 6: CreateWorkerResponse
	(*NodeStatusRequest)(nil),      // 7: NodeStatusRequest
	(*NodeStatusResponse)(nil),     // 8: NodeStatusResponse
	(*DeleteInstanceRequest)(nil),  // 9: DeleteInstanceRequest
	(*DeleteInstanceResponse)(nil), // 10: DeleteInstanceResponse
}
var file_services_model_proto_model_node_proto_depIdxs = []int32{
	2,  // 0: CreateMasterRequest.requirements:type_name -> CreateNodeRequirements
	1,  // 1: CreateMasterResponse.creation_status:type_name -> CreationStatus
	2,  // 2: CreateWorkerRequest.requirements:type_name -> CreateNodeRequirements
	1,  // 3: CreateWorkerResponse.creation_status:type_name -> CreationStatus
	3,  // 4: NodeService.CreateMaster:input_type -> CreateMasterRequest
	5,  // 5: NodeService.CreateWorker:input_type -> CreateWorkerRequest
	7,  // 6: NodeService.NodeStatus:input_type -> NodeStatusRequest
	9,  // 7: NodeService.DeleteInstance:input_type -> DeleteInstanceRequest
	4,  // 8: NodeService.CreateMaster:output_type -> CreateMasterResponse
	6,  // 9: NodeService.CreateWorker:output_type -> CreateWorkerResponse
	8,  // 10: NodeService.NodeStatus:output_type -> NodeStatusResponse
	10, // 11: NodeService.DeleteInstance:output_type -> DeleteInstanceResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_services_model_proto_model_node_proto_init() }
func file_services_model_proto_model_node_proto_init() {
	if File_services_model_proto_model_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_model_proto_model_node_proto_rawDesc), len(file_services_model_proto_model_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_model_proto_model_node_proto_goTypes,
		DependencyIndexes: file_services_model_proto_model_node_proto_depIdxs,
		MessageInfos:      file_services_model_proto_model_node_proto_msgTypes,
	}.Build()
	File_services_model_proto_model_node_proto = out.File
	file_services_model_proto_model_node_proto_goTypes = nil
	file_services_model_proto_model_node_proto_depIdxs = nil
}
