syntax = "proto3";

option go_package = "./services/model/proto-model";

enum Status {
  STATUS_UNSPECIFIED = 0;
  STATUS_AVAILABLE = 1;
  STATUS_UNAVAILABLE = 2;
}

message Empty {}

message CreateNodeRequirements {
  int64 cpu = 1;
  int64 memory = 2;
  int64 storage = 3;
}

// create master
message CreateMasterRequest {
  string token = 1;
  CreateNodeRequirements requirements = 2;
}

message CreateMasterResponse {
  string ip_address = 1;
}

// create worker
message CreateWorkerRequest {
  string token = 1;
  string ip_address = 2;
  CreateNodeRequirements requirements = 3;
}

message CreateWorkerResponse {}

// create instance
message CreateInstanceRequest {
  // top-level name of the cluster
  //
  string name = 1;

  // true if spawning master instance
  // false otherwise
  bool is_master = 2;

  // token for creating k3s cluster
  // only needed when spawning worker
  // token will created when spawning master
  string token = 3;

  // ip address of the master instance
  // only needed when spawning worker
  string ip_address = 4;

  // instance hardware requirements
  int64 cpu = 5;
  int64 memory = 6;
  int64 storage = 7;
}

message CreateInstanceResponse {
  // returns ip address of master instance
  string ip_address = 1;
}

service NodeService {
  rpc CreateMaster(CreateMasterRequest) returns (CreateMasterResponse) {}
  rpc CreateWorker(CreateWorkerRequest) returns (CreateWorkerResponse) {}
  rpc CreateInstance(CreateInstanceRequest) returns (CreateInstanceResponse) {}
  // rpc RegisterNode(RegisterNodeRequest) returns (RegisterNodeResponse) {}
  // rpc ThisNodeStatus(Empty) returns (Temp) {}
  // rpc Status(Empty) returns (NodeStatus) {}
  // rpc StopNode(Empty) returns (Empty) {}
}
