syntax = "proto3";

option go_package = "./services/model/proto-model";

enum Status {
  STATUS_UNSPECIFIED = 0;
  STATUS_AVAILABLE = 1;
  STATUS_UNAVAILABLE = 2;
}

message Empty {}

message CreateNodeRequirements {
  string node_name = 1;
  int64 cpu = 2;
  int64 memory = 3;
  int64 storage = 4;
}

// create master
message CreateMasterRequest {
  string cluster_name = 1;
  string cluster_token = 2;
  CreateNodeRequirements requirements = 3;
}

message CreateMasterResponse {
  string master_ip_address = 1;
  string dashboard_token = 2;
}

// create worker
message CreateWorkerRequest {
  string cluster_name = 1;
  string cluster_token = 2;
  string master_ip_address = 3;
  CreateNodeRequirements requirements = 4;
}

message CreateWorkerResponse {}

// node status
message NodeUsagePercentage {
  // cpu usage percentage
  double cpu_usage_percentage = 1;

  // storage usage percentage
  uint64 storage_available = 2;
  double storage_usage_percentage = 3;

  // memory usage
  uint64 memory_available = 4;
  double memory_usage_percentage = 5;
}

message NodeStatusRequest {}

message NodeStatusResponse {
  NodeUsagePercentage node_usage = 1;
  Status node_status = 2;
}


service NodeService {
  rpc CreateMaster(CreateMasterRequest) returns (CreateMasterResponse) {}
  rpc CreateWorker(CreateWorkerRequest) returns (CreateWorkerResponse) {}
  rpc NodeStatus(NodeStatusRequest) returns (NodeStatusResponse) {}
  // rpc RegisterNode(RegisterNodeRequest) returns (RegisterNodeResponse) {}
  // rpc ThisNodeStatus(Empty) returns (Temp) {}
  // rpc Status(Empty) returns (NodeStatus) {}
  // rpc StopNode(Empty) returns (Empty) {}
}
