syntax = "proto3";

option go_package = "./services/model/proto-model";

enum Status {
  STATUS_UNSPECIFIED = 0;
  STATUS_AVAILABLE = 1;
  STATUS_UNAVAILABLE = 2;
}

message Empty {}

message CreateNodeRequirements {
  string node_name = 1;
  int64 cpu = 2;
  int64 memory = 3;
  int64 storage = 4;
}

// create master
message CreateMasterRequest {
  string cluster_name = 1;
  string cluster_token = 2;
  CreateNodeRequirements requirements = 3;
}

message CreateMasterResponse {
  string master_ip_address = 1;
  string dashboard_token = 2;
}

// create worker
message CreateWorkerRequest {
  string cluster_name = 1;
  string cluster_token = 2;
  string master_ip_address = 3;
  CreateNodeRequirements requirements = 4;
}

message CreateWorkerResponse {}

service NodeService {
  rpc CreateMaster(CreateMasterRequest) returns (CreateMasterResponse) {}
  rpc CreateWorker(CreateWorkerRequest) returns (CreateWorkerResponse) {}
  // rpc RegisterNode(RegisterNodeRequest) returns (RegisterNodeResponse) {}
  // rpc ThisNodeStatus(Empty) returns (Temp) {}
  // rpc Status(Empty) returns (NodeStatus) {}
  // rpc StopNode(Empty) returns (Empty) {}
}
