// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: services/model/proto-model/node.proto

package proto_model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_AVAILABLE   Status = 1
	Status_STATUS_UNAVAILABLE Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_AVAILABLE",
		2: "STATUS_UNAVAILABLE",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_AVAILABLE":   1,
		"STATUS_UNAVAILABLE": 2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_services_model_proto_model_node_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_services_model_proto_model_node_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_services_model_proto_model_node_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_services_model_proto_model_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_services_model_proto_model_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_services_model_proto_model_node_proto_rawDescGZIP(), []int{0}
}

type CreateNodeRequirements struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Cpu           int64                  `protobuf:"varint,2,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        int64                  `protobuf:"varint,3,opt,name=memory,proto3" json:"memory,omitempty"`
	Storage       int64                  `protobuf:"varint,4,opt,name=storage,proto3" json:"storage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNodeRequirements) Reset() {
	*x = CreateNodeRequirements{}
	mi := &file_services_model_proto_model_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNodeRequirements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNodeRequirements) ProtoMessage() {}

func (x *CreateNodeRequirements) ProtoReflect() protoreflect.Message {
	mi := &file_services_model_proto_model_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNodeRequirements.ProtoReflect.Descriptor instead.
func (*CreateNodeRequirements) Descriptor() ([]byte, []int) {
	return file_services_model_proto_model_node_proto_rawDescGZIP(), []int{1}
}

func (x *CreateNodeRequirements) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *CreateNodeRequirements) GetCpu() int64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *CreateNodeRequirements) GetMemory() int64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *CreateNodeRequirements) GetStorage() int64 {
	if x != nil {
		return x.Storage
	}
	return 0
}

// create master
type CreateMasterRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	ClusterName   string                  `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	ClusterToken  string                  `protobuf:"bytes,2,opt,name=cluster_token,json=clusterToken,proto3" json:"cluster_token,omitempty"`
	Requirements  *CreateNodeRequirements `protobuf:"bytes,3,opt,name=requirements,proto3" json:"requirements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMasterRequest) Reset() {
	*x = CreateMasterRequest{}
	mi := &file_services_model_proto_model_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMasterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMasterRequest) ProtoMessage() {}

func (x *CreateMasterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_model_proto_model_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMasterRequest.ProtoReflect.Descriptor instead.
func (*CreateMasterRequest) Descriptor() ([]byte, []int) {
	return file_services_model_proto_model_node_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMasterRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *CreateMasterRequest) GetClusterToken() string {
	if x != nil {
		return x.ClusterToken
	}
	return ""
}

func (x *CreateMasterRequest) GetRequirements() *CreateNodeRequirements {
	if x != nil {
		return x.Requirements
	}
	return nil
}

type CreateMasterResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MasterIpAddress string                 `protobuf:"bytes,1,opt,name=master_ip_address,json=masterIpAddress,proto3" json:"master_ip_address,omitempty"`
	DashboardToken  string                 `protobuf:"bytes,2,opt,name=dashboard_token,json=dashboardToken,proto3" json:"dashboard_token,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateMasterResponse) Reset() {
	*x = CreateMasterResponse{}
	mi := &file_services_model_proto_model_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMasterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMasterResponse) ProtoMessage() {}

func (x *CreateMasterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_model_proto_model_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMasterResponse.ProtoReflect.Descriptor instead.
func (*CreateMasterResponse) Descriptor() ([]byte, []int) {
	return file_services_model_proto_model_node_proto_rawDescGZIP(), []int{3}
}

func (x *CreateMasterResponse) GetMasterIpAddress() string {
	if x != nil {
		return x.MasterIpAddress
	}
	return ""
}

func (x *CreateMasterResponse) GetDashboardToken() string {
	if x != nil {
		return x.DashboardToken
	}
	return ""
}

// create worker
type CreateWorkerRequest struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	ClusterName     string                  `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	ClusterToken    string                  `protobuf:"bytes,2,opt,name=cluster_token,json=clusterToken,proto3" json:"cluster_token,omitempty"`
	MasterIpAddress string                  `protobuf:"bytes,3,opt,name=master_ip_address,json=masterIpAddress,proto3" json:"master_ip_address,omitempty"`
	Requirements    *CreateNodeRequirements `protobuf:"bytes,4,opt,name=requirements,proto3" json:"requirements,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateWorkerRequest) Reset() {
	*x = CreateWorkerRequest{}
	mi := &file_services_model_proto_model_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkerRequest) ProtoMessage() {}

func (x *CreateWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_model_proto_model_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkerRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkerRequest) Descriptor() ([]byte, []int) {
	return file_services_model_proto_model_node_proto_rawDescGZIP(), []int{4}
}

func (x *CreateWorkerRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *CreateWorkerRequest) GetClusterToken() string {
	if x != nil {
		return x.ClusterToken
	}
	return ""
}

func (x *CreateWorkerRequest) GetMasterIpAddress() string {
	if x != nil {
		return x.MasterIpAddress
	}
	return ""
}

func (x *CreateWorkerRequest) GetRequirements() *CreateNodeRequirements {
	if x != nil {
		return x.Requirements
	}
	return nil
}

type CreateWorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkerResponse) Reset() {
	*x = CreateWorkerResponse{}
	mi := &file_services_model_proto_model_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkerResponse) ProtoMessage() {}

func (x *CreateWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_model_proto_model_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkerResponse.ProtoReflect.Descriptor instead.
func (*CreateWorkerResponse) Descriptor() ([]byte, []int) {
	return file_services_model_proto_model_node_proto_rawDescGZIP(), []int{5}
}

// node status
type NodeUsagePercentage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cpu usage percentage
	CpuUsagePercentage float64 `protobuf:"fixed64,1,opt,name=cpu_usage_percentage,json=cpuUsagePercentage,proto3" json:"cpu_usage_percentage,omitempty"`
	// storage usage percentage
	StorageAvailable       uint64  `protobuf:"varint,2,opt,name=storage_available,json=storageAvailable,proto3" json:"storage_available,omitempty"`
	StorageUsagePercentage float64 `protobuf:"fixed64,3,opt,name=storage_usage_percentage,json=storageUsagePercentage,proto3" json:"storage_usage_percentage,omitempty"`
	// memory usage
	MemoryAvailable       uint64  `protobuf:"varint,4,opt,name=memory_available,json=memoryAvailable,proto3" json:"memory_available,omitempty"`
	MemoryUsagePercentage float64 `protobuf:"fixed64,5,opt,name=memory_usage_percentage,json=memoryUsagePercentage,proto3" json:"memory_usage_percentage,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *NodeUsagePercentage) Reset() {
	*x = NodeUsagePercentage{}
	mi := &file_services_model_proto_model_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeUsagePercentage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeUsagePercentage) ProtoMessage() {}

func (x *NodeUsagePercentage) ProtoReflect() protoreflect.Message {
	mi := &file_services_model_proto_model_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeUsagePercentage.ProtoReflect.Descriptor instead.
func (*NodeUsagePercentage) Descriptor() ([]byte, []int) {
	return file_services_model_proto_model_node_proto_rawDescGZIP(), []int{6}
}

func (x *NodeUsagePercentage) GetCpuUsagePercentage() float64 {
	if x != nil {
		return x.CpuUsagePercentage
	}
	return 0
}

func (x *NodeUsagePercentage) GetStorageAvailable() uint64 {
	if x != nil {
		return x.StorageAvailable
	}
	return 0
}

func (x *NodeUsagePercentage) GetStorageUsagePercentage() float64 {
	if x != nil {
		return x.StorageUsagePercentage
	}
	return 0
}

func (x *NodeUsagePercentage) GetMemoryAvailable() uint64 {
	if x != nil {
		return x.MemoryAvailable
	}
	return 0
}

func (x *NodeUsagePercentage) GetMemoryUsagePercentage() float64 {
	if x != nil {
		return x.MemoryUsagePercentage
	}
	return 0
}

type NodeStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatusRequest) Reset() {
	*x = NodeStatusRequest{}
	mi := &file_services_model_proto_model_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatusRequest) ProtoMessage() {}

func (x *NodeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_model_proto_model_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatusRequest.ProtoReflect.Descriptor instead.
func (*NodeStatusRequest) Descriptor() ([]byte, []int) {
	return file_services_model_proto_model_node_proto_rawDescGZIP(), []int{7}
}

type NodeStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeUsage     *NodeUsagePercentage   `protobuf:"bytes,1,opt,name=node_usage,json=nodeUsage,proto3" json:"node_usage,omitempty"`
	NodeStatus    Status                 `protobuf:"varint,2,opt,name=node_status,json=nodeStatus,proto3,enum=Status" json:"node_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatusResponse) Reset() {
	*x = NodeStatusResponse{}
	mi := &file_services_model_proto_model_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatusResponse) ProtoMessage() {}

func (x *NodeStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_model_proto_model_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatusResponse.ProtoReflect.Descriptor instead.
func (*NodeStatusResponse) Descriptor() ([]byte, []int) {
	return file_services_model_proto_model_node_proto_rawDescGZIP(), []int{8}
}

func (x *NodeStatusResponse) GetNodeUsage() *NodeUsagePercentage {
	if x != nil {
		return x.NodeUsage
	}
	return nil
}

func (x *NodeStatusResponse) GetNodeStatus() Status {
	if x != nil {
		return x.NodeStatus
	}
	return Status_STATUS_UNSPECIFIED
}

var File_services_model_proto_model_node_proto protoreflect.FileDescriptor

const file_services_model_proto_model_node_proto_rawDesc = "" +
	"\n" +
	"%services/model/proto-model/node.proto\"\a\n" +
	"\x05Empty\"y\n" +
	"\x16CreateNodeRequirements\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x10\n" +
	"\x03cpu\x18\x02 \x01(\x03R\x03cpu\x12\x16\n" +
	"\x06memory\x18\x03 \x01(\x03R\x06memory\x12\x18\n" +
	"\astorage\x18\x04 \x01(\x03R\astorage\"\x9a\x01\n" +
	"\x13CreateMasterRequest\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\x12#\n" +
	"\rcluster_token\x18\x02 \x01(\tR\fclusterToken\x12;\n" +
	"\frequirements\x18\x03 \x01(\v2\x17.CreateNodeRequirementsR\frequirements\"k\n" +
	"\x14CreateMasterResponse\x12*\n" +
	"\x11master_ip_address\x18\x01 \x01(\tR\x0fmasterIpAddress\x12'\n" +
	"\x0fdashboard_token\x18\x02 \x01(\tR\x0edashboardToken\"\xc6\x01\n" +
	"\x13CreateWorkerRequest\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\x12#\n" +
	"\rcluster_token\x18\x02 \x01(\tR\fclusterToken\x12*\n" +
	"\x11master_ip_address\x18\x03 \x01(\tR\x0fmasterIpAddress\x12;\n" +
	"\frequirements\x18\x04 \x01(\v2\x17.CreateNodeRequirementsR\frequirements\"\x16\n" +
	"\x14CreateWorkerResponse\"\x91\x02\n" +
	"\x13NodeUsagePercentage\x120\n" +
	"\x14cpu_usage_percentage\x18\x01 \x01(\x01R\x12cpuUsagePercentage\x12+\n" +
	"\x11storage_available\x18\x02 \x01(\x04R\x10storageAvailable\x128\n" +
	"\x18storage_usage_percentage\x18\x03 \x01(\x01R\x16storageUsagePercentage\x12)\n" +
	"\x10memory_available\x18\x04 \x01(\x04R\x0fmemoryAvailable\x126\n" +
	"\x17memory_usage_percentage\x18\x05 \x01(\x01R\x15memoryUsagePercentage\"\x13\n" +
	"\x11NodeStatusRequest\"s\n" +
	"\x12NodeStatusResponse\x123\n" +
	"\n" +
	"node_usage\x18\x01 \x01(\v2\x14.NodeUsagePercentageR\tnodeUsage\x12(\n" +
	"\vnode_status\x18\x02 \x01(\x0e2\a.StatusR\n" +
	"nodeStatus*N\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10STATUS_AVAILABLE\x10\x01\x12\x16\n" +
	"\x12STATUS_UNAVAILABLE\x10\x022\xc4\x01\n" +
	"\vNodeService\x12=\n" +
	"\fCreateMaster\x12\x14.CreateMasterRequest\x1a\x15.CreateMasterResponse\"\x00\x12=\n" +
	"\fCreateWorker\x12\x14.CreateWorkerRequest\x1a\x15.CreateWorkerResponse\"\x00\x127\n" +
	"\n" +
	"NodeStatus\x12\x12.NodeStatusRequest\x1a\x13.NodeStatusResponse\"\x00B\x1eZ\x1c./services/model/proto-modelb\x06proto3"

var (
	file_services_model_proto_model_node_proto_rawDescOnce sync.Once
	file_services_model_proto_model_node_proto_rawDescData []byte
)

func file_services_model_proto_model_node_proto_rawDescGZIP() []byte {
	file_services_model_proto_model_node_proto_rawDescOnce.Do(func() {
		file_services_model_proto_model_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_model_proto_model_node_proto_rawDesc), len(file_services_model_proto_model_node_proto_rawDesc)))
	})
	return file_services_model_proto_model_node_proto_rawDescData
}

var file_services_model_proto_model_node_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_services_model_proto_model_node_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_services_model_proto_model_node_proto_goTypes = []any{
	(Status)(0),                    // 0: Status
	(*Empty)(nil),                  // 1: Empty
	(*CreateNodeRequirements)(nil), // 2: CreateNodeRequirements
	(*CreateMasterRequest)(nil),    // 3: CreateMasterRequest
	(*CreateMasterResponse)(nil),   // 4: CreateMasterResponse
	(*CreateWorkerRequest)(nil),    // 5: CreateWorkerRequest
	(*CreateWorkerResponse)(nil),   // 6: CreateWorkerResponse
	(*NodeUsagePercentage)(nil),    // 7: NodeUsagePercentage
	(*NodeStatusRequest)(nil),      // 8: NodeStatusRequest
	(*NodeStatusResponse)(nil),     // 9: NodeStatusResponse
}
var file_services_model_proto_model_node_proto_depIdxs = []int32{
	2, // 0: CreateMasterRequest.requirements:type_name -> CreateNodeRequirements
	2, // 1: CreateWorkerRequest.requirements:type_name -> CreateNodeRequirements
	7, // 2: NodeStatusResponse.node_usage:type_name -> NodeUsagePercentage
	0, // 3: NodeStatusResponse.node_status:type_name -> Status
	3, // 4: NodeService.CreateMaster:input_type -> CreateMasterRequest
	5, // 5: NodeService.CreateWorker:input_type -> CreateWorkerRequest
	8, // 6: NodeService.NodeStatus:input_type -> NodeStatusRequest
	4, // 7: NodeService.CreateMaster:output_type -> CreateMasterResponse
	6, // 8: NodeService.CreateWorker:output_type -> CreateWorkerResponse
	9, // 9: NodeService.NodeStatus:output_type -> NodeStatusResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_services_model_proto_model_node_proto_init() }
func file_services_model_proto_model_node_proto_init() {
	if File_services_model_proto_model_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_model_proto_model_node_proto_rawDesc), len(file_services_model_proto_model_node_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_model_proto_model_node_proto_goTypes,
		DependencyIndexes: file_services_model_proto_model_node_proto_depIdxs,
		EnumInfos:         file_services_model_proto_model_node_proto_enumTypes,
		MessageInfos:      file_services_model_proto_model_node_proto_msgTypes,
	}.Build()
	File_services_model_proto_model_node_proto = out.File
	file_services_model_proto_model_node_proto_goTypes = nil
	file_services_model_proto_model_node_proto_depIdxs = nil
}
