// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.865
package base

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "nodes-grpc-frontend-local/src/components/top-bar"
import "nodes-grpc-frontend-local/src/components/node-list"
import "nodes-grpc-frontend-local/src/entity"

func Page(nodes []entity.Node) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html><head><title>Dashboard</title><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" charset=\"UTF-8\"><link rel=\"stylesheet\" href=\"./assets/styles.css\"><script src=\"./assets/script.js\"></script></head><body class=\"h-screen\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = top_bar.TopBar().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div id=\"container\" class=\"m-8\"><form><div class=\"flex gap-4 py-1\"><div><label for=\"name\">Name:</label> <input type=\"text\" id=\"name\" name=\"name\"></div><div><label for=\"vcpu\">CPU:</label> <select name=\"vcpu\" id=\"vcpu\"><option value=\"1\">1 vCPU</option> <option value=\"2\">2 vCPUs</option> <option value=\"3\">3 vCPUs</option> <option value=\"4\">4 vCPUs</option></select></div><div><label for=\"memory\">Memory:</label> <select name=\"memory\" id=\"memory\"><option value=\"4\">4 GBs</option> <option value=\"8\">8 GBs</option> <option value=\"16\">16 GBs</option></select></div><div><label for=\"storage\">Storage:</label> <select name=\"storage\" id=\"storage\"><option value=\"4\">4 GBs</option> <option value=\"8\">8 GBs</option> <option value=\"16\">16 GBs</option></select></div><div><label>node size</label> <input type=\"number\" id=\"node_size\" name=\"node_size\" min=\"1\" max=\"5\"></div></div><div class=\"flex gap-2\"><button type=\"button\" class=\"p-4 bg-blue-700 rounded-lg text-white hover:cursor-pointer\" onclick=\"sendRequirementJson()\">Create Cluster</button> <button id=\"accessClusterButton\" type=\"button\" class=\"p-4 bg-blue-700 rounded-lg text-white hover:cursor-pointer invisible\">Access Cluster</button></div></form></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = nodelist.NodeList(nodes).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div id=\"wait\" class=\"m-8 font-mono\"></div><div id=\"token\" class=\"m-8 font-mono overflow-hidden text-ellipsis break-words\"></div><div class=\"flex w-full\"><div id=\"kernel-log\" class=\"m-4 font-mono flex-1\"></div><div id=\"cloud-init-log\" class=\"m-4 font-mono flex-1\"></div></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
